# Generated by Django 6.1 on 2026-08-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Code de départ pour les exercices code_challenge'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('multiple_choice', 'Choix multiple'), ('true_false', 'Vrai / Faux'), ('fill_blank', 'Texte à trous'), ('code_order', 'Ordre du code'), ('code_challenge', 'Défi code Python')], default='multiple_choice', max_length=20),
        ),
    ]
