from django.contrib.auth import get_user_model
from django.urls import reverse
from rest_framework.test import APITestCase

from learning.models import Course, Exercise, Lesson, LessonProgress, Unit

User = get_user_model()


class LearningFlowTests(APITestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            username="alice", password="Str0ngPass!42"
        )
        self.course = Course.objects.create(title="Python", order=0)
        self.unit = Unit.objects.create(course=self.course, title="Bases")
        self.lesson = Lesson.objects.create(unit=self.unit, title="Print", xp_reward=10)
        self.ex1 = Exercise.objects.create(
            lesson=self.lesson,
            exercise_type=Exercise.Type.MULTIPLE_CHOICE,
            question="Fonction d'affichage ?",
            choices=["print()", "echo()"],
            correct_answer="print()",
        )
        self.ex2 = Exercise.objects.create(
            lesson=self.lesson,
            exercise_type=Exercise.Type.TRUE_FALSE,
            question="Python est typé dynamiquement.",
            choices=["Vrai", "Faux"],
            correct_answer="Vrai",
        )

    def authenticate(self):
        self.client.force_authenticate(self.user)

    def test_course_slug_autogenerated(self):
        self.assertEqual(self.course.slug, "python")

    def test_course_list_requires_auth(self):
        resp = self.client.get(reverse("course_list"))
        self.assertEqual(resp.status_code, 401)

    def test_course_list(self):
        self.authenticate()
        resp = self.client.get(reverse("course_list"))
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(len(resp.data), 1)
        self.assertEqual(resp.data[0]["title"], "Python")

    def test_course_detail_nested(self):
        self.authenticate()
        resp = self.client.get(
            reverse("course_detail", kwargs={"slug": "python"})
        )
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(len(resp.data["units"]), 1)
        self.assertEqual(len(resp.data["units"][0]["lessons"]), 1)

    def test_lesson_detail_has_exercises(self):
        self.authenticate()
        resp = self.client.get(
            reverse("lesson_detail", kwargs={"pk": self.lesson.pk})
        )
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(len(resp.data["exercises"]), 2)

    def test_complete_lesson_all_correct_awards_xp(self):
        self.authenticate()
        payload = {
            "answers": [
                {"exercise_id": self.ex1.id, "answer": "print()"},
                {"exercise_id": self.ex2.id, "answer": "Vrai"},
            ]
        }
        resp = self.client.post(
            reverse("lesson_complete", kwargs={"pk": self.lesson.pk}),
            payload,
            format="json",
        )
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.data["score"], 100)
        self.assertTrue(resp.data["passed"])
        self.assertEqual(resp.data["xp_gained"], 10)

        self.user.refresh_from_db()
        self.assertEqual(self.user.xp, 10)
        self.assertEqual(self.user.streak_count, 1)

        progress = LessonProgress.objects.get(user=self.user, lesson=self.lesson)
        self.assertTrue(progress.completed)
        self.assertEqual(progress.best_score, 100)

    def test_complete_lesson_failing_gives_no_xp(self):
        self.authenticate()
        payload = {
            "answers": [
                {"exercise_id": self.ex1.id, "answer": "echo()"},
                {"exercise_id": self.ex2.id, "answer": "Faux"},
            ]
        }
        resp = self.client.post(
            reverse("lesson_complete", kwargs={"pk": self.lesson.pk}),
            payload,
            format="json",
        )
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.data["score"], 0)
        self.assertFalse(resp.data["passed"])
        self.assertEqual(resp.data["xp_gained"], 0)

        self.user.refresh_from_db()
        self.assertEqual(self.user.xp, 0)

    def test_answer_case_insensitive(self):
        self.assertTrue(self.ex1.is_correct("PRINT()"))
        self.assertFalse(self.ex1.is_correct("input()"))


class AuthTests(APITestCase):
    def test_register_and_login(self):
        resp = self.client.post(
            reverse("register"),
            {"username": "bob", "password": "Str0ngPass!42", "email": "b@e.com"},
            format="json",
        )
        self.assertEqual(resp.status_code, 201)

        resp = self.client.post(
            reverse("login"),
            {"username": "bob", "password": "Str0ngPass!42"},
            format="json",
        )
        self.assertEqual(resp.status_code, 200)
        self.assertIn("access", resp.data)

    def test_me_endpoint(self):
        user = User.objects.create_user(username="carol", password="Str0ngPass!42")
        self.client.force_authenticate(user)
        resp = self.client.get(reverse("me"))
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp.data["username"], "carol")
        self.assertEqual(resp.data["hearts"], User.MAX_HEARTS)
