# Generated by Django 6.1 on 2026-08-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('estimated_minutes', models.PositiveIntegerField(default=15)),
                ('color_theme', models.CharField(default='#58CC02', max_length=20)),
                ('icon', models.CharField(default='terminal', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('xp_reward', models.PositiveIntegerField(default=15)),
                ('order', models.PositiveIntegerField(default=0)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.track')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('prompt', models.TextField()),
                ('answer_format', models.CharField(default='text', max_length=60)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('estimated_minutes', models.PositiveIntegerField(default=5)),
                ('is_daily_featured', models.BooleanField(default=False)),
                ('reference_solution', models.TextField()),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='learning.track')),
            ],
            options={
                'ordering': ['-is_daily_featured', 'estimated_minutes', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField()),
                ('lesson_type', models.CharField(choices=[('theory', 'Theory'), ('code_quiz', 'Code Quiz'), ('debug', 'Debug Challenge'), ('project', 'Project Sprint')], default='theory', max_length=20)),
                ('theory', models.TextField()),
                ('instructions', models.TextField()),
                ('starter_code', models.TextField(blank=True)),
                ('solution_hint', models.TextField(blank=True)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.module')),
            ],
            options={
                'ordering': ['order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('module', 'slug'), name='unique_lesson_slug_per_module')],
            },
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('track', 'slug'), name='unique_module_slug_per_track'),
        ),
    ]
