# Generated by Django 5.2.17 on 2026-08-25 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('host', models.CharField(max_length=255, verbose_name='adresse IP / hostname')),
                ('port', models.PositiveIntegerField(default=8728, verbose_name='port API')),
                ('username', models.CharField(max_length=100, verbose_name='utilisateur API')),
                ('password_encrypted', models.TextField(verbose_name='mot de passe (chiffré)')),
                ('hotspot_server', models.CharField(blank=True, default='hotspot1', max_length=100, verbose_name='serveur hotspot')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('connection_status', models.CharField(choices=[('unknown', 'Non testé'), ('online', 'En ligne'), ('offline', 'Hors ligne'), ('error', 'Erreur')], default='unknown', max_length=20)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'routeur',
                'verbose_name_plural': 'routeurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
