# Generated by Django 5.2.17 on 2026-08-25 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0002_hotspotlogintemplate'),
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='login_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routers', to='hotspots.hotspotlogintemplate', verbose_name='template login'),
        ),
    ]
