# Generated by Django 5.2.17 on 2026-08-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0002_router_login_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='snmp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
