# Generated by Django 5.2.17 on 2026-08-26 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0003_router_latitude_router_longitude_router_snmp_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='snmp_community',
            field=models.CharField(blank=True, default='public', max_length=64),
        ),
        migrations.CreateModel(
            name='RadiusServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('auth_port', models.PositiveIntegerField(default=1812)),
                ('acct_port', models.PositiveIntegerField(default=1813)),
                ('secret_encrypted', models.TextField(blank=True)),
                ('nas_identifier', models.CharField(blank=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_export_path', models.CharField(blank=True, max_length=255)),
                ('last_export_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radius_servers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'serveur RADIUS',
                'verbose_name_plural': 'serveurs RADIUS',
            },
        ),
    ]
