# Generated by Django 5.2.17 on 2026-08-26 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teammembership'),
        ('hotspots', '0003_hotspotlogintemplate_ad_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='can_generate_vouchers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_manage_routers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_manage_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='can_view_reports',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='hotspots.pointofsale'),
        ),
        migrations.AddField(
            model_name='user',
            name='gdpr_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_reseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reseller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reseller_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(default='staff', max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
