# Generated by Django 6.1 on 2026-08-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reminder_hour',
            field=models.PositiveSmallIntegerField(default=19, help_text='Heure du rappel quotidien (0-23)'),
        ),
    ]
