# Generated by Django 5.2.17 on 2026-08-25 14:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom affiché')),
                ('mikrotik_profile', models.CharField(help_text='Nom du profil sur le routeur (ex: 1hour, 1day)', max_length=100, verbose_name='profil MikroTik')),
                ('validity_seconds', models.PositiveIntegerField(default=3600, help_text='Durée de validité en secondes (3600 = 1h)', verbose_name='validité (secondes)')),
                ('data_limit_bytes', models.BigIntegerField(blank=True, help_text='0 ou vide = illimité', null=True, verbose_name='limite data (octets)')),
                ('shared_users', models.PositiveIntegerField(default=1, verbose_name='utilisateurs partagés')),
                ('price', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='prix vente (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='routers.router')),
            ],
            options={
                'verbose_name': 'profil hotspot',
                'verbose_name_plural': 'profils hotspot',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VoucherBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=14)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_batches', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='hotspots.hotspotprofile')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_batches', to='routers.router')),
            ],
            options={
                'verbose_name': 'lot de vouchers',
                'verbose_name_plural': 'lots de vouchers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code voucher')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('unused', 'Non utilisé'), ('active', 'Actif'), ('expired', 'Expiré'), ('disabled', 'Désactivé')], default='unused', max_length=20)),
                ('sold_price', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('synced_to_mikrotik', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='hotspots.hotspotprofile')),
                ('router', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='routers.router')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='hotspots.voucherbatch')),
            ],
            options={
                'verbose_name': 'voucher',
                'verbose_name_plural': 'vouchers',
                'ordering': ['-created_at'],
            },
        ),
    ]
