# Generated by Django 5.2.17 on 2026-08-25 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotLoginTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('html_body', models.TextField(verbose_name='HTML')),
                ('is_system', models.BooleanField(default=False, verbose_name='template système')),
                ('is_active', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#0d6efd', max_length=20)),
                ('background_color', models.CharField(default='#1a1d23', max_length=20)),
                ('wifi_name', models.CharField(blank=True, default='WiFiZone', max_length=120)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Null = template système partagé', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'template login hotspot',
                'verbose_name_plural': 'templates login hotspot',
                'ordering': ['name'],
                'unique_together': {('owner', 'slug')},
            },
        ),
    ]
