# Generated by Django 5.2.17 on 2026-08-26 08:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0002_hotspotlogintemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotlogintemplate',
            name='ad_video_url',
            field=models.URLField(blank=True, help_text='Vidéo/pub avant login'),
        ),
        migrations.AddField(
            model_name='hotspotlogintemplate',
            name='html_logout',
            field=models.TextField(blank=True, verbose_name='HTML logout'),
        ),
        migrations.AddField(
            model_name='hotspotlogintemplate',
            name='html_status',
            field=models.TextField(blank=True, verbose_name='HTML status'),
        ),
        migrations.AddField(
            model_name='hotspotlogintemplate',
            name='locale',
            field=models.CharField(default='fr', help_text='fr, en, ha', max_length=10),
        ),
        migrations.AddField(
            model_name='hotspotprofile',
            name='parent_queue',
            field=models.CharField(blank=True, help_text='Parent queue MikroTik', max_length=100),
        ),
        migrations.AddField(
            model_name='voucher',
            name='commission_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='voucher',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_sold', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('balance', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('operator', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_voucher', models.PositiveIntegerField(default=1)),
                ('vouchers_per_reward', models.PositiveIntegerField(default=10, help_text='Nombre de vouchers pour 1 récompense')),
                ('reward_description', models.CharField(default='1 voucher gratuit', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('operator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_sale', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'point de vente',
                'verbose_name_plural': 'points de vente',
            },
        ),
        migrations.AddField(
            model_name='voucher',
            name='point_of_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='hotspots.pointofsale'),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tx_type', models.CharField(choices=[('topup', 'Recharge manuelle'), ('debit', 'Débit voucher'), ('loyalty', 'Points fidélité')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='hotspots.customerwallet')),
            ],
        ),
    ]
