# Generated by Django 5.2.17 on 2026-08-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspots', '0003_hotspotlogintemplate_ad_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotlogintemplate',
            name='is_marketplace_public',
            field=models.BooleanField(default=False, help_text='Partager sur la marketplace templates'),
        ),
        migrations.AddField(
            model_name='hotspotlogintemplate',
            name='login_delay_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Délai cyber café avant login (secondes)'),
        ),
        migrations.AddField(
            model_name='hotspotlogintemplate',
            name='marketplace_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
