# Generated by Django 5.2.17 on 2026-08-25 14:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price_monthly', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='prix mensuel (FCFA)')),
                ('max_routers', models.PositiveIntegerField(default=1, verbose_name='routeurs max')),
                ('max_vouchers_month', models.PositiveIntegerField(default=100, verbose_name='vouchers / mois')),
                ('max_profiles', models.PositiveIntegerField(default=5, verbose_name='profils max')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='fonctionnalités')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='mis en avant')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'forfait',
                'verbose_name_plural': 'forfaits',
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Essai'), ('active', 'Actif'), ('past_due', 'Impayé'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='trial', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('vouchers_used_this_month', models.PositiveIntegerField(default=0)),
                ('month_reset_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
            },
        ),
    ]
