# Generated by Django 5.2.17 on 2026-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_staff',
            field=models.PositiveIntegerField(default=0, help_text='0 = pas de multi-utilisateurs', verbose_name='employés max'),
        ),
    ]
