# Generated by Django 6.1 on 2026-08-12 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='Ada', max_length=120)),
                ('target_role', models.CharField(default='Developpeuse full-stack', max_length=120)),
                ('daily_goal_minutes', models.PositiveIntegerField(default=20)),
                ('streak_days', models.PositiveIntegerField(default=5)),
                ('total_xp', models.PositiveIntegerField(default=180)),
                ('hearts', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('estimated_minutes', models.PositiveIntegerField(default=8)),
                ('xp_reward', models.PositiveIntegerField(default=15)),
                ('challenge_count', models.PositiveIntegerField(default=3)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='terminal', max_length=32)),
                ('difficulty', models.CharField(choices=[('beginner', 'Debutant'), ('intermediate', 'Intermediaire'), ('advanced', 'Avance')], default='beginner', max_length=20)),
                ('color_start', models.CharField(default='#1D4ED8', max_length=7)),
                ('color_end', models.CharField(default='#7C3AED', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('exercise_type', models.CharField(choices=[('multiple_choice', 'Choix multiple'), ('terminal', 'Terminal'), ('code_order', 'Ordre du code')], default='multiple_choice', max_length=32)),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='learning.lesson')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.track'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Verrouille'), ('available', 'Disponible'), ('completed', 'Termine')], default='locked', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('last_practiced_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='learning.lesson')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='learning.learnerprofile')),
            ],
            options={
                'ordering': ['lesson__sort_order', 'lesson__title'],
                'unique_together': {('profile', 'lesson')},
            },
        ),
    ]
