# -*- coding: utf-8 -*-
"""Énoncé B — Examen blanc Linux Essentials 010-160 — Niger Certify (propriétaire)."""

from enonce_a import COMMON

EXAM_B = {
    **COMMON,
    "version": "B",
    "code": "NC-LE-BLANC-B-2026",
    "title": "Examen blanc Linux Essentials",
    "subtitle": "Linux Professional Institute  ·  Exam 010-160  ·  objectifs v1.6",
    "duration": "60 minutes",
    "n_questions": 40,
    "bareme": "52 points (A 28 + B 12 + C 12)",
    "seuil": "67 %  ≈  35 / 52",
    "parts": [
        {
            "title": "Partie A — QCM (une seule bonne réponse)",
            "intro": "Questions 1 à 28. Cochez une seule case. Barème : 1 point par question. Sujet distinct de la version A.",
            "questions": [
                {
                    "n": 1,
                    "points": 1,
                    "stem": "Ubuntu LTS se distingue surtout par :",
                    "choices": [
                        ("A", "Un cycle de support long (typiquement 5 ans sur la version LTS)."),
                        ("B", "L'usage exclusif de paquets RPM."),
                        ("C", "L'absence de dépôt apt."),
                        ("D", "Un noyau Windows NT."),
                    ],
                    "answer": "A",
                    "explain": "LTS = Long Term Support. Ubuntu = Debian/.deb.",
                },
                {
                    "n": 2,
                    "points": 1,
                    "stem": "Quel serveur web open source est cité aux objectifs Linux Essentials aux côtés d'Apache HTTPD ?",
                    "choices": [
                        ("A", "IIS uniquement"),
                        ("B", "NGINX"),
                        ("C", "Exchange"),
                        ("D", "SharePoint"),
                    ],
                    "answer": "B",
                    "explain": "Apache HTTPD et NGINX (plus MariaDB/MySQL, Samba, NFS).",
                },
                {
                    "n": 3,
                    "points": 1,
                    "stem": "ownCloud et Nextcloud sont principalement :",
                    "choices": [
                        ("A", "Des bureaux GNOME"),
                        ("B", "Des solutions de cloud / partage de fichiers auto-hébergées"),
                        ("C", "Des compilateurs C"),
                        ("D", "Des systèmes de fichiers noyau"),
                    ],
                    "answer": "B",
                    "explain": "Objectif 1.2 : Nextcloud, ownCloud.",
                },
                {
                    "n": 4,
                    "points": 1,
                    "stem": "Sur une distribution Red Hat / Fedora, quelle commande installe un paquet depuis les dépôts (dnf) ?",
                    "choices": [
                        ("A", "apt-get install httpd"),
                        ("B", "sudo dnf install httpd"),
                        ("C", "dpkg -i httpd.deb"),
                        ("D", "pacman -S httpd (défaut RHEL)"),
                    ],
                    "answer": "B",
                    "explain": "yum/dnf = famille Red Hat. apt/dpkg = Debian.",
                },
                {
                    "n": 5,
                    "points": 1,
                    "stem": "Une licence BSD (permissive) permet surtout, par rapport à la GPL :",
                    "choices": [
                        ("A", "D'exiger que tout dérivé reste sous BSD copyleft strict identique à la GPL."),
                        ("B", "Une réutilisation plus souple, y compris dans des produits propriétaires, sous conditions d'attribution."),
                        ("C", "D'interdire toute copie."),
                        ("D", "De déposer un brevet FSF automatique."),
                    ],
                    "answer": "B",
                    "explain": "BSD/MIT = permissives ; GPL = copyleft fort.",
                },
                {
                    "n": 6,
                    "points": 1,
                    "stem": "FLOSS désigne :",
                    "choices": [
                        ("A", "Un système de fichiers Linux."),
                        ("B", "Free/Libre and Open Source Software."),
                        ("C", "Un protocole réseau FCoE."),
                        ("D", "Le chargeur de démarrage uniquement."),
                    ],
                    "answer": "B",
                    "explain": "FOSS / FLOSS = logiciel libre et open source.",
                },
                {
                    "n": 7,
                    "points": 1,
                    "stem": "Pour rendre une variable visible des processus enfants du shell :",
                    "choices": [
                        ("A", "setuid VAR"),
                        ("B", "export VAR=valeur"),
                        ("C", "chmod +x VAR"),
                        ("D", "mount VAR"),
                    ],
                    "answer": "B",
                    "explain": "export place la variable dans l'environnement.",
                },
                {
                    "n": 8,
                    "points": 1,
                    "stem": "<font face='NC-Mono'>type ls</font> sert principalement à :",
                    "choices": [
                        ("A", "Afficher le manuel section 5."),
                        ("B", "Indiquer comment le shell résout ls (alias, builtin, fichier)."),
                        ("C", "Formater un disque."),
                        ("D", "Changer le PATH."),
                    ],
                    "answer": "B",
                    "explain": "type / which : nature de la commande.",
                },
                {
                    "n": 9,
                    "points": 1,
                    "stem": "Où trouve-t-on souvent de la documentation supplémentaire des paquets ?",
                    "choices": [
                        ("A", "/usr/share/doc/"),
                        ("B", "/etc/shadow"),
                        ("C", "/proc/irq"),
                        ("D", "/dev/null"),
                    ],
                    "answer": "A",
                    "explain": "Objectif 2.2 : man, info, /usr/share/doc/, locate.",
                },
                {
                    "n": 10,
                    "points": 1,
                    "stem": "<font face='NC-Mono'>ls -lR</font> :",
                    "choices": [
                        ("A", "Liste récursive (sous-répertoires) au format long."),
                        ("B", "Supprime récursivement."),
                        ("C", "Change le propriétaire."),
                        ("D", "Archive en tar."),
                    ],
                    "answer": "A",
                    "explain": "-l long, -R recursive.",
                },
                {
                    "n": 11,
                    "points": 1,
                    "stem": "Le répertoire personnel d'un utilisateur est le plus souvent indiqué dans :",
                    "choices": [
                        ("A", "/etc/hosts"),
                        ("B", "Le champ home de /etc/passwd (ex. /home/awa)"),
                        ("C", "/var/log/syslog"),
                        ("D", "/boot/grub"),
                    ],
                    "answer": "B",
                    "explain": "passwd : login:x:UID:GID:gecos:home:shell.",
                },
                {
                    "n": 12,
                    "points": 1,
                    "stem": "<font face='NC-Mono'>mv cours.pdf ~/Documents/</font> :",
                    "choices": [
                        ("A", "Copie le PDF et conserve l'original."),
                        ("B", "Déplace (ou renomme) le fichier vers Documents."),
                        ("C", "Crée un lien symbolique."),
                        ("D", "Compresse en gzip."),
                    ],
                    "answer": "B",
                    "explain": "mv = move/rename. cp = copy.",
                },
                {
                    "n": 13,
                    "points": 1,
                    "stem": "Le glob <font face='NC-Mono'>exo?.txt</font> correspond à :",
                    "choices": [
                        ("A", "exo suivi d'exactement un caractère, puis .txt"),
                        ("B", "n'importe quelle chaîne, comme *"),
                        ("C", "Uniquement exo.txt"),
                        ("D", "Une regex étendue équivalente à .+"),
                    ],
                    "answer": "A",
                    "explain": "? = un caractère (glob). * = joker multiple.",
                },
                {
                    "n": 14,
                    "points": 1,
                    "stem": "Pour extraire <font face='NC-Mono'>archive.tar.bz2</font> :",
                    "choices": [
                        ("A", "tar xjf archive.tar.bz2"),
                        ("B", "tar czf archive.tar.bz2"),
                        ("C", "gzip -d uniquement, sans tar"),
                        ("D", "unzip archive.tar.bz2"),
                    ],
                    "answer": "A",
                    "explain": "x extract, j bzip2, f fichier. z = gzip, J = xz.",
                },
                {
                    "n": 15,
                    "points": 1,
                    "stem": "<font face='NC-Mono'>zip devoirs.zip *.odt</font> puis extraction :",
                    "choices": [
                        ("A", "unzip devoirs.zip"),
                        ("B", "tar xzf devoirs.zip"),
                        ("C", "gunzip devoirs.zip"),
                        ("D", "bzip2 -d devoirs.zip"),
                    ],
                    "answer": "A",
                    "explain": "zip/unzip (objectif 3.1), distinct de tar/gzip.",
                },
                {
                    "n": 16,
                    "points": 1,
                    "stem": "<font face='NC-Mono'>wc -l fichier.txt</font> affiche :",
                    "choices": [
                        ("A", "Le nombre de lignes."),
                        ("B", "Le checksum MD5."),
                        ("C", "Les permissions."),
                        ("D", "Le propriétaire UID."),
                    ],
                    "answer": "A",
                    "explain": "wc : lines, words, bytes (-l -w -c).",
                },
                {
                    "n": 17,
                    "points": 1,
                    "stem": "<font face='NC-Mono'>cmd1 | cmd2</font> :",
                    "choices": [
                        ("A", "Écrit stdout de cmd1 dans un fichier nommé cmd2."),
                        ("B", "Envoie stdout de cmd1 sur stdin de cmd2."),
                        ("C", "Exécute cmd2 seulement si cmd1 échoue."),
                        ("D", "Redirige stderr de cmd2 vers /dev/null."),
                    ],
                    "answer": "B",
                    "explain": "Pipe = stdout → stdin.",
                },
                {
                    "n": 18,
                    "points": 1,
                    "stem": "Après une commande, <font face='NC-Mono'>echo $?</font> affiche :",
                    "choices": [
                        ("A", "Le PID."),
                        ("B", "Le code de sortie (0 = succès par convention)."),
                        ("C", "Le premier argument."),
                        ("D", "Le PATH."),
                    ],
                    "answer": "B",
                    "explain": "Exit status. 0 = OK, ≠0 = erreur.",
                },
                {
                    "n": 19,
                    "points": 1,
                    "stem": "Pour qu'un script <font face='NC-Mono'>./hello.sh</font> s'exécute, il faut généralement :",
                    "choices": [
                        ("A", "Uniquement qu'il soit dans /etc."),
                        ("B", "Le bit d'exécution (chmod +x) et un shebang ou un appel bash hello.sh."),
                        ("C", "Qu'il soit compilé avec gcc."),
                        ("D", "Qu'il appartienne à root."),
                    ],
                    "answer": "B",
                    "explain": "chmod +x ; ou bash script.sh sans +x.",
                },
                {
                    "n": 20,
                    "points": 1,
                    "stem": "Les journaux système classiques se trouvent surtout dans :",
                    "choices": [
                        ("A", "/etc"),
                        ("B", "/var/log"),
                        ("C", "/home"),
                        ("D", "/boot"),
                    ],
                    "answer": "B",
                    "explain": "/var/log (syslog, messages, journald selon distro).",
                },
                {
                    "n": 21,
                    "points": 1,
                    "stem": "<font face='NC-Mono'>ps</font> et <font face='NC-Mono'>top</font> servent à :",
                    "choices": [
                        ("A", "Gérer les partitions."),
                        ("B", "Observer les processus (instantané vs interactif)."),
                        ("C", "Configurer l'IP."),
                        ("D", "Compiler le noyau."),
                    ],
                    "answer": "B",
                    "explain": "ps = snapshot ; top = rafraîchi. free = mémoire.",
                },
                {
                    "n": 22,
                    "points": 1,
                    "stem": "<font face='NC-Mono'>dmesg</font> affiche principalement :",
                    "choices": [
                        ("A", "L'historique Bash de l'utilisateur."),
                        ("B", "Le tampon de messages du noyau (matériel, boot, erreurs)."),
                        ("C", "La liste des paquets apt."),
                        ("D", "Les mails de /var/mail."),
                    ],
                    "answer": "B",
                    "explain": "dmesg = kernel ring buffer.",
                },
                {
                    "n": 23,
                    "points": 1,
                    "stem": "Pour afficher les adresses IP des interfaces (commande moderne) :",
                    "choices": [
                        ("A", "ip addr show"),
                        ("B", "chmod 777 /etc/hosts"),
                        ("C", "useradd -D"),
                        ("D", "tar tf /"),
                    ],
                    "answer": "A",
                    "explain": "ip addr / ip route. ifconfig = héritage encore cité.",
                },
                {
                    "n": 24,
                    "points": 1,
                    "stem": "Le fichier <font face='NC-Mono'>/etc/hosts</font> sert à :",
                    "choices": [
                        ("A", "Stocker les mots de passe chiffrés."),
                        ("B", "Associer localement des noms d'hôtes à des adresses IP."),
                        ("C", "Lister les modules initramfs."),
                        ("D", "Définir le sticky bit."),
                    ],
                    "answer": "B",
                    "explain": "Résolution statique, en complément ou avant DNS.",
                },
                {
                    "n": 25,
                    "points": 1,
                    "stem": "Un compte <b>système</b> (daemon) se caractérise souvent par :",
                    "choices": [
                        ("A", "UID 0 et shell bash interactif obligatoire."),
                        ("B", "UID bas, shell nologin/false, pas de connexion bureau."),
                        ("C", "Appartenance obligatoire au groupe sudo."),
                        ("D", "Un home dans /home identique à un stagiaire."),
                    ],
                    "answer": "B",
                    "explain": "Comptes service : www-data, nobody… pas pour un humain.",
                },
                {
                    "n": 26,
                    "points": 1,
                    "stem": "Quelle commande crée un utilisateur (outil bas niveau LPI) ?",
                    "choices": [
                        ("A", "useradd stagiaire"),
                        ("B", "chmod stagiaire"),
                        ("C", "ping stagiaire"),
                        ("D", "tar cf stagiaire"),
                    ],
                    "answer": "A",
                    "explain": "useradd / groupadd / passwd. adduser = wrapper Debian.",
                },
                {
                    "n": 27,
                    "points": 1,
                    "stem": "<font face='NC-Mono'>chown awa:staff rapport.txt</font> :",
                    "choices": [
                        ("A", "Change le propriétaire et le groupe du fichier."),
                        ("B", "Change uniquement les bits rwx."),
                        ("C", "Crée l'utilisateur awa."),
                        ("D", "Archive le fichier."),
                    ],
                    "answer": "A",
                    "explain": "chown user:group. chmod = mode.",
                },
                {
                    "n": 28,
                    "points": 1,
                    "stem": "<font face='NC-Mono'>/var/tmp</font> par rapport à <font face='NC-Mono'>/tmp</font> :",
                    "choices": [
                        ("A", "Les fichiers de /var/tmp sont généralement plus persistants (survivent souvent au reboot)."),
                        ("B", " /var/tmp est toujours en RAM uniquement."),
                        ("C", "Seul root peut y écrire, jamais le sticky bit."),
                        ("D", "C'est un lien obligatoire vers /boot."),
                    ],
                    "answer": "A",
                    "explain": "Objectif 5.4 : /tmp, /var/tmp, sticky bit. /tmp souvent tmpfs.",
                },
            ],
        },
        {
            "title": "Partie B — Plusieurs réponses",
            "intro": "Questions 29 à 34. Toutes les bonnes cases doivent être cochées, aucune mauvaise. Barème : 2 points, tout ou rien.",
            "questions": [
                {
                    "n": 29,
                    "points": 2,
                    "multi": True,
                    "n_correct": 2,
                    "stem": "Sélectionnez <b>deux</b> langages / technologies de développement listés aux objectifs Linux Essentials.",
                    "choices": [
                        ("A", "Python"),
                        ("B", "PHP"),
                        ("C", "Visual Basic 6 obligatoire sur le noyau"),
                        ("D", "Delphi propriétaire comme unique option web"),
                        ("E", "COBOL comme shell par défaut Bash"),
                    ],
                    "answer": "A, B",
                    "explain": "C, Java, JavaScript, Perl, shell, Python, PHP.",
                },
                {
                    "n": 30,
                    "points": 2,
                    "multi": True,
                    "n_correct": 2,
                    "stem": "Sélectionnez <b>deux</b> commandes de consultation d'aide.",
                    "choices": [
                        ("A", "man grep"),
                        ("B", "info bash"),
                        ("C", "fdisk /dev/sda (destructive, pas de l'aide)"),
                        ("D", "passwd -d root"),
                        ("E", "rm -rf /"),
                    ],
                    "answer": "A, B",
                    "explain": "man et info (plus /usr/share/doc et locate).",
                },
                {
                    "n": 31,
                    "points": 2,
                    "multi": True,
                    "n_correct": 2,
                    "stem": "Sélectionnez <b>deux</b> commandes qui affichent le début ou la fin d'un fichier texte.",
                    "choices": [
                        ("A", "head"),
                        ("B", "tail"),
                        ("C", "userdel"),
                        ("D", "mkfs"),
                        ("E", "chroot"),
                    ],
                    "answer": "A, B",
                    "explain": "head/tail (souvent -n). less/cat aussi en 3.2.",
                },
                {
                    "n": 32,
                    "points": 2,
                    "multi": True,
                    "n_correct": 2,
                    "stem": "Sélectionnez <b>deux</b> composants matériels cités aux objectifs (4.2).",
                    "choices": [
                        ("A", "Carte mère et processeur"),
                        ("B", "Disques HDD/SSD et partitions /dev/sd*"),
                        ("C", "Uniquement le cloud, jamais de disque local"),
                        ("D", "Le fichier /etc/passwd comme bus PCI"),
                        ("E", "GPL comme type de RAM"),
                    ],
                    "answer": "A, B",
                    "explain": "Motherboard, CPU, PSU, optical, HDD/SSD, drivers.",
                },
                {
                    "n": 33,
                    "points": 2,
                    "multi": True,
                    "n_correct": 2,
                    "stem": "Sélectionnez <b>deux</b> commandes utiles pour diagnostiquer le réseau local.",
                    "choices": [
                        ("A", "ping"),
                        ("B", "host (requête DNS)"),
                        ("C", "chmod 000 /"),
                        ("D", "tar czf /"),
                        ("E", "nano /dev/sda"),
                    ],
                    "answer": "A, B",
                    "explain": "ping, host, ip addr, ip route, ss/netstat.",
                },
                {
                    "n": 34,
                    "points": 2,
                    "multi": True,
                    "n_correct": 2,
                    "stem": "Sélectionnez <b>deux</b> commandes liées aux sessions utilisateurs.",
                    "choices": [
                        ("A", "who"),
                        ("B", "w"),
                        ("C", "mkswap"),
                        ("D", "lvcreate"),
                        ("E", "iptables-save obligatoire LE"),
                    ],
                    "answer": "A, B",
                    "explain": "who, w, last, id. (5.1)",
                },
            ],
        },
        {
            "title": "Partie C — Scénarios et sorties de commandes",
            "intro": "Questions 35 à 40. Lisez la sortie avant de répondre. Barème : 2 points par question.",
            "questions": [
                {
                    "n": 35,
                    "points": 2,
                    "stem": "PATH=/usr/local/bin:/usr/bin:/bin. La commande <font face='NC-Mono'>cat</font> sera cherchée d'abord dans :",
                    "choices": [
                        ("A", "/bin uniquement, toujours"),
                        ("B", "/usr/local/bin puis /usr/bin puis /bin"),
                        ("C", "Le répertoire courant, toujours en premier par défaut Bash"),
                        ("D", "/etc"),
                    ],
                    "answer": "B",
                    "explain": "PATH est parcouru de gauche à droite. « . » n'y figure généralement pas.",
                },
                {
                    "n": 36,
                    "points": 2,
                    "stem": "Quelle commande affiche les 10 dernières lignes puis suit le fichier (suivi) ?",
                    "code": "fichier : /var/log/syslog",
                    "choices": [
                        ("A", "head -n 10 /var/log/syslog"),
                        ("B", "tail -f /var/log/syslog"),
                        ("C", "cut -d: -f1 /var/log/syslog"),
                        ("D", "sort /var/log/syslog | uniq"),
                    ],
                    "answer": "B",
                    "explain": "tail -f = follow. head = début.",
                },
                {
                    "n": 37,
                    "points": 2,
                    "stem": "Ce script est lancé : <font face='NC-Mono'>./salut.sh Awa</font>. Quelle sortie ?",
                    "code": "#!/bin/bash\necho \"Bonjour $1\"",
                    "choices": [
                        ("A", "Bonjour $1"),
                        ("B", "Bonjour Awa"),
                        ("C", "Bonjour ./salut.sh"),
                        ("D", "Erreur : $1 n'existe pas"),
                    ],
                    "answer": "B",
                    "explain": "$1 = premier argument = Awa. $0 = nom du script.",
                },
                {
                    "n": 38,
                    "points": 2,
                    "stem": "Sortie <font face='NC-Mono'>ls -ld /tmp</font> :",
                    "code": "drwxrwxrwt 12 root root 4096 Aug 27 10:00 /tmp",
                    "choices": [
                        ("A", "Répertoire world-writable avec sticky bit (t)."),
                        ("B", "Fichier ordinaire appartenant à un user UID 1000."),
                        ("C", "Lien symbolique cassé."),
                        ("D", "Pas de droit d'exécution, donc non traversable."),
                    ],
                    "answer": "A",
                    "explain": "d = directory, t = sticky, rwx pour tous + t.",
                },
                {
                    "n": 39,
                    "points": 2,
                    "stem": "Extrait de <font face='NC-Mono'>/etc/passwd</font> :",
                    "code": "www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin",
                    "choices": [
                        ("A", "Compte interactif UID 0."),
                        ("B", "Compte système UID 33, shell nologin (pas de login interactif)."),
                        ("C", "Mot de passe en clair « x »."),
                        ("D", "Home = /root."),
                    ],
                    "answer": "B",
                    "explain": "x = mot de passe dans shadow. nologin = service web.",
                },
                {
                    "n": 40,
                    "points": 2,
                    "stem": "<font face='NC-Mono'>grep '^root' /etc/passwd</font> :",
                    "choices": [
                        ("A", "Toutes les lignes contenant root n'importe où."),
                        ("B", "Les lignes qui commencent par root (regex ^)."),
                        ("C", "Supprime le compte root."),
                        ("D", "Équivalent à grep -v root."),
                    ],
                    "answer": "B",
                    "explain": "^ = début de ligne. grep -v = inverse.",
                },
            ],
        },
    ],
    "minilab": {
        "title": "Mini-lab papier (optionnel formateur — hors barème 52 pts)",
        "intro": (
            "Durée indicative 15 minutes. Sujet distinct de la version A. "
            "Le formateur peut attribuer jusqu'à 10 points bonus."
        ),
        "context_title": "Contexte",
        "topo": (
            "Utilisateur : formateur peut simuler root pour useradd.\n"
            "Objectif : compte, archive zip, recherche, lien symbolique."
        ),
        "tasks": [
            "Créer l'utilisateur demo (useradd) avec home, puis définir un mot de passe (passwd).",
            "Dans le home de demo : mkdir cours ; echo 'LPI' > cours/intro.txt ; zip -r cours.zip cours.",
            "Afficher les lignes de /etc/passwd qui commencent par demo (grep).",
            "Créer un lien symbolique /tmp/intro vers cours/intro.txt (depuis le home demo).",
            "Donner à intro.txt les droits 640 et le groupe users (chmod / chown).",
        ],
        "correction": (
            "sudo useradd -m demo\n"
            "sudo passwd demo\n"
            "sudo -u demo bash -c 'mkdir -p ~/cours && echo LPI > ~/cours/intro.txt && zip -r ~/cours.zip ~/cours'\n"
            "grep '^demo' /etc/passwd\n"
            "sudo -u demo ln -s /home/demo/cours/intro.txt /tmp/intro\n"
            "sudo chmod 640 /home/demo/cours/intro.txt\n"
            "sudo chown demo:users /home/demo/cours/intro.txt"
        ),
    },
}
